### ISSUE TITLE
Run on a single machine

### ISSUE THREAD

**Issue by Jarvis-K** [NVIDIA/runx#2]
How can I use runx without farm settings? Or how can I set the farm in ubuntu? I am confused about the 'submit_job' refer.

**Comment by ajtao** [comment]
We've assumed that people would only use runx to run jobs in a farm, but I think it does make sense to support non-farm use. 'submit_job' is the tool we use to submit jobs to a farm.

I'll create an option to run run jobs interactively on a single machine ...

**Comment by daddydrac** [comment]
@ajtao  Can we deploy this to kubernetes?

**Comment by Jarvis-K** [comment]
I have made some simple modifications [code](https://github.com/Jarvis-K/runx) to use it in a single machine and docker settings.  The issue would be closed for a while.
