### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by jasonmusespresso** [NVIDIA/runx#3]
Thanks for your great work. Would you support Logger Objects in the future?

**Comment by ajtao** [comment]
Right now there's the logx.msg() functionality, which is logging to logfile. Maybe you were looking for more functionality than that?

**Comment by jasonmusespresso** [comment]
Say, I set the logging as follows:
```#!/usr/bin/env python3
import logging

logging.basicConfig(level=logging.INFO,
        format='%(asctime)s %(levelname)s %(threadName)-10s %(message)')
logging.info('This will get logged')
```
Could I configure runx so that it formats the log information in a same fashion? 

Thanks!

**Comment by ajtao** [comment]
I see, right, I chose to keep the logging very basic, without using the logging package, to keep the implementation minimal. It would probably not be terribly difficult to change to use the logging package, so i'll make a note of this, but not sure when i can get to it.

**Comment by jasonmusespresso** [comment]
Thanks!
