### ISSUE TITLE
Problem of SUBMID_CMD: submit_job in .runx

### ISSUE THREAD

**Issue by TheoRenLi** [NVIDIA/runx#5]
When i run this command: python -m runx.runx sweep.yml, there is a problem below, why?
"""Copying codebase to ./logs/sweep/witty-fennec_2020.05.27_21.05 ...
Submitting job sweep_witty-fennec_2020.05.27_21.05
/bin/sh: 1: submit_job: not found """

**Comment by ajtao** [comment]
Hello, if you update your code and try the examples again, please try the interactive mode:

> pip install --upgrade runx
> cd examples
> python -m runx.runx mnist.yml -i

That should work!

**Comment by TheoRenLi** [comment]
it works now, Thanks!

**Comment by anyuzoey** [comment]
Hi,

Same problem here with the newest version runx.

/bin/sh: 1: cd: can't cd to logs/train_cityscapes/ocrnet.HRNet_Mscale_attractive-gharial_2020.10.29_04.59/code

Any idea how to fix it?
