### ISSUE TITLE
simple example not working

### ISSUE THREAD

**Issue by jasonmusespresso** [NVIDIA/runx#7]
Here is a simple test script:
 main.py
```
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--text')
args = parser.parse_args()

print(args.text)

```

sweep.yml
``` 
cmd: 'python main.py'

hparams:
  text: ['job1', 'job2']

```

The simple example in the readme is not working.
I got this error:
```
$ python -m runx.runx sweep.yml
...
raise('can\'t find file ./.runx or ~/.config/runx.yml config files')
```

**Comment by ajtao** [comment]
Hi Jiajun,

Sorry to not respond earlier!

Could you please update your runx (pip install --upgrade runx). Then try your example but make sure examples/.runx is in your directory (or place it in ~/.config/runx.yml).

**Comment by Freed-Wu** [comment]
In <https://github.com/NVIDIA/runx#introduction-example>, simple example don't introduce anything about `.runx`.

And if `LOGROOT` is defined, runx can work. Why not define a default `LOGROOT` (such as `~/.cache/runx`)? It can make user less confused.
